name: Main Workflow

on:
  push:
    branches: ["main"]

jobs:
  call-reusable:
    uses: ./.github/workflows/original_workflow.yaml

  reusable_from_another_repo:
    uses: SwarnaAnjani/reuseable/.github/workflows/another_repo_workflow.yaml@main


